### ISSUE TITLE
npm install --setup-dev fails

### ISSUE THREAD

**Issue by serverhorror** [biasmv/pv#77]
Hello,

I tried to follow http://pv.readthedocs.org/en/latest/intro.html#installing-from-git but it bails out. I couldn't the installation to work as described 

Clean Checkout from Master:

```
$ git remote -v
origin  https://github.com/biasmv/pv (fetch)
origin  https://github.com/biasmv/pv (push)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
$ git log -1
commit 02bf4a10f08289edbd52c2ab7de8f1b5d340d5e4
Author: Marco Biasini <mvbiasini@gmail.com>
Date:   Sat Jan 31 12:07:00 2015 +0100

    increase code coverage by also testing rendering of views
```

Fedora 20 System Install (node/npm):

```
$ which npm node
/bin/npm
/bin/node
$ node -v
v0.10.33
$ npm -v
1.3.6
$ npm install --setup-dev
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid version: "1.4-dev"
npm ERR!     at Object.module.exports.fixVersionField (/usr/lib/node_modules/normalize-package-data/lib/fixer.js:175:13)
npm ERR!     at /usr/lib/node_modules/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/node_modules/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/node_modules/read-package-json/read-json.js:310:33)
npm ERR!     at then (/usr/lib/node_modules/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/lib/node_modules/read-package-json/read-json.js:299:40
npm ERR!     at fs.js:271:14
npm ERR!     at /usr/lib/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.2-201.fc20.x86_64
npm ERR! command "node" "/bin/npm" "install" "--setup-dev"
npm ERR! cwd /data/cscratch/marcherm/npm-test/pv
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /data/cscratch/marcherm/npm-test/pv/npm-debug.log
npm ERR! not ok code 0
```

Latest Install from binaries (node/npm):

```
$ which npm node
~/scratch/npm-test/node-v0.10.36-linux-x64/bin/npm
~/scratch/npm-test/node-v0.10.36-linux-x64/bin/node
$ node -v
v0.10.36
$ npm -v
1.4.28
$ npm install --setup-dev
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid version: "1.4-dev"
npm ERR!     at Object.module.exports.fixVersionField (/data/cscratch/marcherm/npm-test/node-v0.10.36-linux-x64/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:183:13)
npm ERR!     at /data/cscratch/marcherm/npm-test/node-v0.10.36-linux-x64/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/data/cscratch/marcherm/npm-test/node-v0.10.36-linux-x64/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
npm ERR!     at final (/data/cscratch/marcherm/npm-test/node-v0.10.36-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
npm ERR!     at then (/data/cscratch/marcherm/npm-test/node-v0.10.36-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /data/cscratch/marcherm/npm-test/node-v0.10.36-linux-x64/lib/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
npm ERR!     at evalmachine.<anonymous>:272:14
npm ERR!     at /data/cscratch/marcherm/npm-test/node-v0.10.36-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.2-201.fc20.x86_64
npm ERR! command "/net/home/marcherm/scratch/npm-test/node-v0.10.36-linux-x64/bin/node" "/net/home/marcherm/scratch/npm-test/node-v0.10.36-linux-x64/bin/npm" "install" "--setup-dev"
npm ERR! cwd /data/cscratch/marcherm/npm-test/pv
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /data/cscratch/marcherm/npm-test/pv/npm-debug.log
npm ERR! not ok code 0
```

**Comment by biasmv** [comment]
Thanks for the report. Apparently npm needs version numbers to have a patch number. I've made small fix by adding a "0" at the end of the version number. 

Just let me know if it works for you.

Best,
Marco

**Comment by andreassteffen** [comment]
works for me now. thanks, Andreas.
